# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo', 'all', 'draw_n']

# %% ../nbs/00_core.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 7
import numpy as np

def all(a, # Input array or object that can be converted to an array.
        axis, # Axis or axes along which a logical AND reduction is performed (default: all).
        out, # Alternate output array in which to place the result.
        keepdims, # Leave reduced one-dimensional axes in the result?
        where, # Elements to include in reduction. See `numpy.ufunc.reduce` for details. New in version 1.20.0.
        ): # A new boolean or array, or a reference to `out` if its specified.
    "Test whether all array elements along a given axis evaluate to `True`."
    ...
    
def draw_n(n:int, # Number of cards to draw
           replace:bool=True # Draw with replacement?
          )->list: # List of cards
    "Draw `n` cards."
